


/*
 * 数据如下：
 * {
      name:'周处除三害',
      grade:7.4,
      actors:['阮经天','袁富华','陈以文','王净'],
      nation:'中国台湾',
      runtime:134,
      imgurl:$r('app.media.film1')
    },
    {
      name:'第二十条',
      grade:7.9,
      actors:['雷佳音','马丽','赵丽颖','高叶'],
      nation:'中国大陆',
      runtime:141,
      imgurl:$r('app.media.film2')
    },
    {
      name:'飞驰人生2',
      grade:7.9,
      actors:['沈腾','范丞丞','尹正','张本煜'],
      nation:'中国大陆',
      runtime:121,
      imgurl:$r('app.media.film3')
    },
    {
      name:'热辣滚烫',
      grade:7.9,
      actors:['贾玲','雷佳音','张小斐','杨紫'],
      nation:'中国大陆',
      runtime:129,
      imgurl:$r('app.media.film4')
    },
    {
      name:'功夫熊猫4',
      grade:7.1,
      actors:['杰克·布莱克','奥卡菲娜','关继威'],
      nation:'中国台湾',
      runtime:94,
      imgurl:$r('app.media.film5')
    }
    * 根据数据定义接口，并将数据以列表渲染的方式渲染到页面中
 * */
@Entry
@Component
struct Index {
  build() {

  }
}

