@Entry
@Component
struct List_Learn {
  build(){
    Column(){
      //根组件
      List({space:10}){
        ListItem(){
          Text('文字')
            .width(100)
            .height(100)
            .backgroundColor(Color.Orange)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Green)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Blue)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(100)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Red)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(100)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Transparent)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(100)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Yellow)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Gray)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Green)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Blue)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(100)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Red)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(100)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Transparent)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Green)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Blue)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(100)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Red)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(100)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Transparent)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Green)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Blue)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(100)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Red)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(100)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Transparent)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Green)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Blue)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(100)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Red)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(100)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Transparent)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }
      }
      .backgroundColor(Color.Gray)
      // .listDirection(Axis.Horizontal)//控制主轴方向
      .lanes(3)//行数
      .width(400)
      .scrollBar(BarState.Auto)//控制滚动条
      .divider({
        strokeWidth:2,
        color:Color.White,
        startMargin:20,
        endMargin:50
      })//分割线属性

    }
  }
}