@Entry
@Component
struct List_Learn {
  build(){
    Column(){
      //根组件
      List(){
        ListItem(){
          Text('文字')
            .width(100)
            .height(100)
            .backgroundColor(Color.Orange)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Green)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Blue)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(100)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Red)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(100)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Transparent)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(100)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Yellow)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Gray)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Green)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Blue)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(100)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Red)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(100)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Transparent)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Green)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Blue)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(100)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Red)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(100)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Transparent)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Green)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Blue)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(100)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Red)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(100)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Transparent)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Green)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Blue)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(100)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Red)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(100)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Transparent)
        }

        ListItem(){
          Text('文字')
            .width(100)
            .height(50)
            .backgroundColor(Color.Pink)
        }
      }
      // .listDirection(Axis.Horizontal)//控制主轴方向
      .lanes(2)//行数

    }
  }
}